### ISSUE TITLE
프로세스 실행 시 자원제한 및 비동기 처리 문제

### ISSUE THREAD

**Issue by Jinmo** [Jinmo/AssemblyLearner#1]
flask 내에서 한 요청이 어떻게 처리되는지 몰라서 비동기쪽은 잘 모르겠지만..
일단 자원제한은 linux라면 setrlimit으로 가능할것같습니다.

tool/tracer 쪽에 추가하는게 쉬워보입니다.
대신 실행 시 옵션을 줘야되겠죠.

**Comment by chop-ch0p** [comment]
https://github.com/eventlet/eventlet/blob/5a4a7ead2435025e2c727c902d7e985be0204417/eventlet/green/subprocess.py

eventlet 을 사용하시면 subprocess 부분이 비동기 처리될겁니다. :D  

찾아보니 monkey_patch 만 호출해도 기본적인 io 는 비동기로 바뀐다고하네요.

**Comment by Jinmo** [comment]
@Ch0p 오오 그렇군요! 감사합니다! 확인해보니 비동기처리가 제대로 되고 있었네요.

**Comment by Jinmo** [comment]
일단은 alarm으로 실행 시간 제한을 구현했습니다. (1초)
signal 관련 시스템콜은 지금으로서 막혀있으므로 작동은 할것같습니다.
setrlimit으로 바꾼 후 다시 close하려고 합니다.

**Comment by Jinmo** [comment]
자원 제한은 된 것 같고, 비동기는 celery로 처리하고 있습니다!
