### ISSUE TITLE
현재 문제 풀기 ui 완성도가 어떻게 되나요?

### ISSUE THREAD

**Issue by chop-ch0p** [Jinmo/AssemblyLearner#10]
문제 컴파일 및 정답 체크 하는 워커 프로토타이핑을 했는데 테스트가 필요해서

문제 풀기 ui완성되면 dev 브랜치로 머지부탁드립니다.

머지되면 job que 에 넣는 부분까지 해서 테스트 후 풀리퀘 드리겠습니다.

**Comment by chop-ch0p** [comment]
tracer.c, execv.s 컴파일 명령어도 부탁드립니다. 최초에 실행할때 체크해서 컴파일 하고 시작하도록 하려고합니다.

**Comment by Jinmo** [comment]
출력창 빼고 대충은 다 만들어진거같아요! (요청 넣는부분 포함)

**Comment by Jinmo** [comment]
tracer argv입니다.
`'too/tracer', '실행파일 경로', 'stdin으로 들어갈 입력파일 경로', '출력파일 경로'`
입니다.

**Comment by Jinmo** [comment]
문제 UI 상황을 조금 자세하게 설명드립니다.

일단 클라이언트 단에서는 정답 여부에 따라 메세지 뜨는 부분까지 완료되었구요, 동작은 아래와 같습니다.

/problem/문제번호/run에 XHR 요청 보냄 (POST, 데이터: code=코드)
응답: JSON

``` js
{
status: ('solved': 정답, 'fail': 실패, 'compileError': 컴파일 에러),
error: 'compileError 시 메세지'
}
```

응답 데이터에 출력은 아직 포함시키지 않았지만 포함시킨다면 output 정도가 될거같네요!
처리부분은 static/js/problem.js에 있습니다.

**Comment by Jinmo** [comment]
#16, #17 에 의해 닫힘
