### ISSUE TITLE
로그인창과 가입창 구분 되도록 ui변경 필요

### ISSUE THREAD

**Issue by jen6** [Jinmo/AssemblyLearner#20]
구분이 잘 안되요 고쳐주세요!

**Comment by Jinmo** [comment]
#21 에서 언급됨:

해결 방안
1. 추가 필드 넣기
   - 비밀번호 확인
   - 이메일
2. 색 바꾸기

고민 좀 해봐야겠군요!

**Comment by Jinmo** [comment]
대충 만든거 같습니다
