### ISSUE TITLE
SQLite concurrency 문제

### ISSUE THREAD

**Issue by Jinmo** [Jinmo/AssemblyLearner#23]
```
Traceback (most recent call last):
  File "./worker.py", line 5, in <module>
    jobqueue.cli()
  File "/home/assemblylearner/=/asmlearner/library/jobqueue/sqlite.py", line 60, in cli
    q.dequeue()
  File "/home/assemblylearner/=/asmlearner/library/jobqueue/sqlite.py", line 31, in dequeue
    job = db.query('SELECT * FROM queue LIMIT 1', isSingle=True)
  File "/home/assemblylearner/=/asmlearner/library/database/sqlite.py", line 17, in query
    cur = self._db.execute(query)
sqlite3.OperationalError: database is locked

```

넵 그렇습니다.
내장된 sqlite3 모듈을 wrapping해서 바로 호출시켜주고 fetch시켜주는 class 패턴으로 현재 작업중인데요, 문제는 이게 멀티스레드일 경우 지원을 안해주거나 여러 프로세스에서 동시에 접근할 때 잘 지원을 안해주거든요.
1. 멀티스레드일 경우 접근
   지금 flask를 제 서버에서는 threaded=True 로 돌리고 있습니다.
2. 멀티프로세스일 경우 접근
   워커 프로세스에서 지금 sqlite3 큐로 임시로 바꿨거든요. 하여튼 이럴 경우 다른 프로세스에서 sqlite DB에 접근하는 경우 locked 에러가 나면서 위의 에러로 꺼집니다. 문제죠.

사실 sqlite3이 한번에 여러 쪽에서 접근하도록 만들어진 DB인지는 잘 모르겠습니다. 아니라는 의견들이 조금 보이네요, 구글링해보니까..

그렇기 때문에
1. DB를 교체한다
   가능은 합니다. 하지만 서버 기반의 DB로 바꿀 경우 DB 연결 구조를 약간 점검해봐야 될 필요성은 있습니다.
2. wrapper 클래스 수정
   wrapper 클래스를 수정한다면 문제 1번은 producer-consumer 패턴으로 수정할 수 있을거같구요, 큐로 만들 수도 있을거같습니다. 하지만 문제 2번은 해결하지 못합니다. 뭐 이 부분은 워커 프로세스에서 수정해주면 되는 부분이긴 합니다.

**Comment by chop-ch0p** [comment]
제가 DB 라이브러리 쪽을 조금 더 추상화 하려던 이유가 바로이겁니다.. sqlite 는 보통 어플리케이션 하나가 한번의 접근할때 유용한거지 동시에 접근할경우 문제가 발생해서였죠... mysql 같은 놈으로 변경작업을 시험이 끝나고 진행해보도록하겠습니다 :D

**Comment by Jinmo** [comment]
@Ch0p :+1:

**Comment by junorouse** [comment]
아직 해결 되었나 모르겠네요.
sqlite3 경우는 파일에 직접적으로 읽고 쓰다보니 여러 쓰레드에서 동시에 접근할 수 없는걸로 알고있습니다. ㅜㅜ

DB에 넣을 자원들을 global변수와 string으로 serialize 할 수도있고, 다른 데이터베이스를 쓰시면 될거같습니다.

다른 몇몇 프로젝트를 보니 레이스컨디션이 발생하지 않는 요청이라면, HTTP request나 웹소켓을 사용하여 플라스크 세션단에서 처리를 하더라구요.

**Comment by Jinmo** [comment]
@junorouse DB에 저장되어야 하는 데이터들이기때문에 sqlalchemy로 포팅하는것이 좋을거같읍니다... 흑흑
언젠간 하겠습니다

**Comment by Jinmo** [comment]
이제 sqlalchemy를 사용하고 있습니다.
