### ISSUE TITLE
리팩토링계획은 없으신가요

### ISSUE THREAD

**Issue by chop-ch0p** [Jinmo/AssemblyLearner#3]
현재 한 파일에 너무 코드가 집중되어있어서... URL 라우팅, DB접근, 문제실행 을 분리했으면하는데 어떻게 생각하시나요?

**Comment by Jinmo** [comment]
생각중이긴 한데 flask를 유지할지 django로 갈아탈지 아직 갈팡질팡한 상황이라 둘 중 하나로 가게 된다면 이루어질거같아요!

**Comment by Jinmo** [comment]
일단은 flask로 유지해보려고 합니다! django 배우면 그때 바꿔야겠네요..
리팩토링은 대충
/routes.py
/database.py
/model.py
/process.py
로 만들고 문제는 클래스로 만들어봐야겠네요.

**Comment by Jinmo** [comment]
문제 정보를 db에 넣는것도 고려해봐야겠네요.

**Comment by Jinmo** [comment]
세션정보를 클래스화해서 User 클래스로 만들려고 했지만 flask는 session 정보를 json으로 요구하기때문에 부적절할것같습니다. 일단 유저에 대한 클래스화는 보류해야겠네요. 이건 django 패턴인거같아요.

어려운 리팩토링의 세계..

**Comment by chop-ch0p** [comment]
ㅎㅎㅎ 리팩토링은 항상 어렵습니다... flask 에 MVC 개념을 도입해보는건 어떠실런지요 ㅎㅎ

**Comment by Jinmo** [comment]
11c58cb 부터 시작된 리팩토링이 기능 구현 상으로는 완료되었으므로 이 이슈는 닫겠습니다. (#22)

수고하셨습니다!!!
